name: Test annotation

on: 
  pull_request:
    types: [opened, reopened, synchronize]

jobs:

  annotate-pr:
    runs-on: ubuntu-latest
    name: Aaaah
    steps:
      - name: Running index.js file maybe...
        uses: https://github.com/schauhan-2/k8s.manifests-sync-action
        with:
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}
